name: RUN puppeteer

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: 'Mona the Octocat'
          id: hello
      - name: Take photo of github.com
        uses: "lannonbr/puppeteer-screenshot-action@1.0.0"
        with:
          url: https://github.com
