name: RUN puppeteer

on:
  schedule:
    - cron: '8,18,58 16-18 * 1 *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm ci
      - run: make
      - run: date
      - run: cp 2020-07*json my-artifact/
      - name: use artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: json
