name: Collect today's SB on schedule

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - run: npm ci
      - run: make
        env:
          VM: azure
      - run: make docs/index.html
        env:
          VM: azure
      - run: date
      - name: use artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: artifact
